CREATE TABLE USER_A (
	USER_ID INTEGER PRIMARY KEY,
	EMAIL VARCHAR(30) NOT NULL, 
	PASSWORD VARCHAR(15), 
	LASTNAME VARCHAR(15) NOT NULL, 
	TYPE_A ENUM('CANDIDATE','ADMIN','EMPLOYER') NOT NULL, 
	STATUS SET('ACTIVE') NOT NULL
);

CREATE TABLE CANDIDATE(
	CANDIDATE_ID INTEGER PRIMARY KEY,
	FIRSTNAME VARCHAR(15),
	LASTNAME VARCHAR(15),
	USER_ID LONG FOREIGN KEY
);