CREATE TABLE candidate(candidateId INT PRIMARY KEY,
	firstName VARCHAR(45) NOT NULL,
	lastName VARCHAR(45)) NOT NULL,
	userId LONG FOREIGN KEY
	);
	
CREATE TABLE user(userID INT PRIMARY KEY,
	email VARCHAR(45) NOT NULL,
	password VARCHAR(12) NOT NULL,
	`type` ENUM('CANDIDATE', 'ADMIN', 'EMPLOYER') NOT NULL,
	status SET('ACTIVE')
	);
